services:
  clustertest:
    image: bee42/clustertest
    build:
      context: .
      dockerfile: Dockerfile
  tomcat:
    build:
      context: tomcat
      dockerfile: Dockerfile
    image: bee42/tomcat:11
    ports:
      - "8080"
      - "8009"
    volumes_from:
      - clustertest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

