global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'httpd-status'
  static_configs:
  - targets: [ 'httpd:9117' ]
- job_name: 'httpd-modjk'
  static_configs:
  - targets: [ 'httpd:9114' ] # If Prometheus runs in Docker on Mac/Windows
- job_name: 'tomcat'
  static_configs:
  - targets: [ 'tomcat:8004' ] # If Prometheus runs in Docker on Mac/Windows
